name: lundedev-core

services:
  lundedev-core:
    container_name: lundedev-core
    image: vegardlu/lundedev-core:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8085:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
      - ALLOWED_CLIENT_IDS=${GOOGLE_CLIENT_ID}
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json:ro
