name: postgres

services:
  postgres:
    container_name: postgres
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-lundedev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lundedev_secret}
      POSTGRES_DB: ${POSTGRES_DB:-lundedev}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    name: postgres_data_v18
